# Generated by Django 5.1.1 on 2024-09-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_remove_file_file_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-id'], 'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
    ]
